services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=samir
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./mongo_data:/data/db

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://samir:123456@mongo:27017/mydatabase?authSource=admin
    depends_on:
      - mongo


